### ISSUE TITLE
Conflict between an expression parenthesis syntax and call syntax

### ISSUE THREAD

**Issue by kagamilove0707** [macro-peg/macro_peg#16]
Here is a tiny example:

```
STRING = STRING_MACRO("\"") / STRING_MACRO("'");
STRING_MACRO(Q) = Q (!(Q / "\\") . / "\\" .)* Q;
```

This grammar accepts general two types string literal (`"..."` and `'...'`), however it produces such an error on current implementation:

``` scala
scala> import com.github.kmizu.macro_peg._
scala> import MacroPEGRunner._
scala> import MacroPEGParser._
scala> :paste
val grammar = parse(
  """
    | STRING = STRING_MACRO("\"") / STRING_MACRO("'");
    | STRING_MACRO(Q) = Q (!(Q / "\\") . / "\\" .)* Q;
  """.stripMargin
)
^D
scala> val evaluator = MacroPEGEvaluator(grammar)
scala> evaluator.evaluate("'foo'", 'STRING)
java.lang.ClassCastException: com.github.kmizu.macro_peg.Ast$Str cannot be cast to com.github.kmizu.macro_peg.Ast$Fun
  at com.github.kmizu.macro_peg.MacroPEGEvaluator.com$github$kmizu$macro_peg$MacroPEGEvaluator$$evaluateIn$1(MacroPEGEvaluator.scala:44)
  at com.github.kmizu.macro_peg.MacroPEGEvaluator.com$github$kmizu$macro_peg$MacroPEGEvaluator$$evaluateIn$1(MacroPEGEvaluator.scala:58)
  at com.github.kmizu.macro_peg.MacroPEGEvaluator.com$github$kmizu$macro_peg$MacroPEGEvaluator$$evaluateIn$1(MacroPEGEvaluator.scala:34)
  at com.github.kmizu.macro_peg.MacroPEGEvaluator.com$github$kmizu$macro_peg$MacroPEGEvaluator$$evaluateIn$1(MacroPEGEvaluator.scala:32)
  at com.github.kmizu.macro_peg.MacroPEGEvaluator.eval(MacroPEGEvaluator.scala:79)
  at com.github.kmizu.macro_peg.MacroPEGEvaluator.evaluate(MacroPEGEvaluator.scala:113)
  ... 42 elided
```

This cause is conflict between an expression parenthesis syntax and call syntax, so `Q (!(Q / "\\") . / "\\" .)` was parsed as a call syntax however I expected this is a sequence of the identifier `Q` and an expression `(!(Q / "\\") . / "\\" .)`.

I think it will be solved: the call syntax must not contain white space between an identifier and a parenthesis `(`.

Or, you can analyze a grammar definition: then, an identifier expects following a parenthesis as arguments list if the value of this identifier is the rule requiring arguments, otherwise not. However, I think this is too complex to solve it.

**Comment by kmizu** [comment]
In 0.0.10, the above example is parsed correctly.  See #18

**Comment by kmizu** [comment]
@kagamilove0707 In Macro PEG 0.0.10, the above example is parsed correctly.  See #18
